
[[block]]
block = "speedtest"
interval = 1800

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "battery"
interval = 10
format = "{percentage}%"

[[block]]
block = "time"
format = "%a %d/%m %R"
interval = 60


